config:
  autonomous-sre-gpu:runpodApiKey:
    secure: AAABAA+QqbsWVUVyXqu+ggRNQ1TLRlHDjYRwQgFl2WMQGm6wtGzB08vagLUCD7chL835ZhrbgKOU+kPQwKpJR4TVC/LuIVum5O+mOIXKC1w7ug==
  autonomous-sre-gpu:dockerRegistry: docker.io/riccee
  autonomous-sre-gpu:dockerUsername: riccee
  autonomous-sre-gpu:dockerPassword:
    secure: AAABAFUGKAa6X2t7WL7yUj1+A1PVChFgmSk52LetC2EO1uUuPzi/8/dv/utjwAF/1nmjI1MtNgi4Vh2MrbvT6bw2XO0=
  autonomous-sre-gpu:hfToken:
    secure: AAABAJppkf2j+CpnFSonDA24XI1dUWO/myYKo5p+RmS64FSCW4P/3rAghGC30LlzhFf1qf/NJJ4HktI8G8eTRiat+/yT
  autonomous-sre-gpu:imageTag: latest
